// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdPZLKbrgg-c3UoIpFnTsq4RormyLn5I',
    appId: '1:187764339120:web:fb220945b461491c792675',
    messagingSenderId: '187764339120',
    projectId: 'testlogin-60433',
    authDomain: 'testlogin-60433.firebaseapp.com',
    databaseURL: 'https://testlogin-60433-default-rtdb.firebaseio.com',
    storageBucket: 'testlogin-60433.firebasestorage.app',
    measurementId: 'G-L19XYHFQ38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmPSyCDWRFaTGWkfPkbNp0VnwOfiqHvx4',
    appId: '1:187764339120:android:5920dae6f571484f792675',
    messagingSenderId: '187764339120',
    projectId: 'testlogin-60433',
    databaseURL: 'https://testlogin-60433-default-rtdb.firebaseio.com',
    storageBucket: 'testlogin-60433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJrQnzP6N-Mh3sXmTvGfMHyY6Zc9Ja8NE',
    appId: '1:187764339120:ios:8da292a2a70f3960792675',
    messagingSenderId: '187764339120',
    projectId: 'testlogin-60433',
    databaseURL: 'https://testlogin-60433-default-rtdb.firebaseio.com',
    storageBucket: 'testlogin-60433.firebasestorage.app',
    iosBundleId: 'com.example.creator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJrQnzP6N-Mh3sXmTvGfMHyY6Zc9Ja8NE',
    appId: '1:187764339120:ios:8da292a2a70f3960792675',
    messagingSenderId: '187764339120',
    projectId: 'testlogin-60433',
    databaseURL: 'https://testlogin-60433-default-rtdb.firebaseio.com',
    storageBucket: 'testlogin-60433.firebasestorage.app',
    iosBundleId: 'com.example.creator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfdPZLKbrgg-c3UoIpFnTsq4RormyLn5I',
    appId: '1:187764339120:web:e5d781e8f764b8f9792675',
    messagingSenderId: '187764339120',
    projectId: 'testlogin-60433',
    authDomain: 'testlogin-60433.firebaseapp.com',
    databaseURL: 'https://testlogin-60433-default-rtdb.firebaseio.com',
    storageBucket: 'testlogin-60433.firebasestorage.app',
    measurementId: 'G-2LQKSX5R7Y',
  );
}
